---
title: "p8105_hw3_kq2127"
author: "Kristal Quispe"
date: "10/12/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(p8105.datasets)
```

## Problem 1

```{r}
data("instacart")

instacart %>% 
  group_by(aisle_id) %>% 
  summarize(n_obs = n()) %>% 
  arrange(desc(n_obs))


instacart %>%
  group_by(aisle_id) %>%
  summarize(n_obs = n()) %>% 
  filter(n_obs > 1000) %>% 
  ggplot(aes(x = aisle_id, y = n_obs)) + 
    geom_point(color = "red", alpha = .5) +
  labs(
    title = "Items Ordered per Aisle",
    x = "Aisle ID",
    y = "Items Ordered (#)"
  ) +
  scale_y_continuous(
    breaks = c(1000, 50000, 150000)
  )

#look into font size

instacart %>%
  group_by(aisle_id, product_name) %>%
  summarize(n_obs = n()) %>% 
  arrange(aisle_id, desc(n_obs)) %>% 
  mutate(rank = min_rank(-n_obs)) %>% 
  filter(rank == 1 | rank ==2 | rank ==3) %>% 
  select(Aisle = aisle_id, Product = product_name, Count = n_obs) %>% 
  knitr::kable()


instacart %>% 
  filter(product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream" ) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(
    mean_hod = mean(order_hour_of_day)
         )%>% 
  pivot_wider(names_from = order_dow, values_from = mean_hod)%>% 
  knitr::kable()

# need to add a mutate with sun-sat for 0-6

```

Data set instacart has 1384617 observations and 15 variables.There are 134 aisles, and aisle number 83 has the most items ordered from (150609).


## Problem 2

Data Cleaning 
```{r}
data("brfss_smart2010")

pb2_df =
  brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health", response %in% c ("Poor", "Fair", "Good", "Excellent")) %>% 
  mutate(response = as.factor(response)) 

```

Using the dataset...
```{r}
pb2_df %>% 
  filter( year == 2002) %>% 
  group_by(locationabbr) %>%
  summarize(
    n_unique = n_distinct(locationdesc))%>%  
  filter(n_unique >= 7)

pb2_df %>% 
  filter( year == 2010) %>% 
  group_by(locationabbr) %>%
  summarize(
    n_unique = n_distinct(locationdesc))%>%  
  filter(n_unique >= 7)

```

In 2002 the following states were observed at 7 or more locations: CT, FL, MA, NC, NJ and PA. In 2010 the following states were observed at 7 or more locations:CA, CO, FL, MA, MD, NC, NE, NJ, NY, OH, PA, SC, TX and WA. 
```{r}
pb2_df %>% 
  filter(response == "Excellent") %>% 
  group_by(year, locationabbr) %>% 
  summarize(mean_dv = mean(data_value)) %>% 
  ggplot(aes(x = year, y = mean_dv, color = locationabbr)) + 
  geom_point() +
  geom_line() + 
  theme(legend.position = "bottom")
```


```{r}
pb2_df %>% 
  filter( year == 2006 | year == 2010, locationabbr == "NY") %>%
  ggplot(aes(x = response, y = data_value, color = year)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(~ year)
```

## Problem 3


```{r}
pb3_df = 
  read_csv(
    file = "./data/accel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    day_type = case_when(
      day  %in% c ("Saturday", "Sunday") ~ "Weekend",
      day  %in% c ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday") ~ "Weekday",
      TRUE      ~"" 
    )) %>% 
  select(week, day_id, day, day_type, everything())

```

